// Shared types and constants for the "Conceptos" tab of the Consola de Revisión.
// Concept pairs (ES/EN) generated by the model land in `concept_queue`; reviewers
// approve, reject (with a reason) or correct them. The pair_es/pair_en payloads
// are free-form JSON whose shape may change, so they are typed as opaque records
// and rendered generically.

export const CONCEPT_ESTADOS = [
  "pendiente",
  "aprobado",
  "corregido",
  "rechazado",
] as const;
export type ConceptEstado = (typeof CONCEPT_ESTADOS)[number];

export const CONCEPT_ACTIONS = ["aprobar", "rechazar", "corregir"] as const;
export type ConceptAction = (typeof CONCEPT_ACTIONS)[number];

// Free-form concept payload — never assume fixed keys.
export type ConceptPair = Record<string, unknown>;

export interface ConceptRow {
  id: string;
  slug: string;
  concepto_tipo: string | null;
  pair_es: ConceptPair;
  pair_en: ConceptPair;
  estado: ConceptEstado;
  modelo: string | null;
  judge_score: number | null;
  run_id: string | null;
  reviewer_id: string | null;
  reviewed_at: string | null;
  notas: string | null;
  correccion: ConceptCorreccion | null;
  created_at: string;
}

// Stored in `correccion` (jsonb) when a reviewer corrects a concept.
export interface ConceptCorreccion {
  antes: { pair_es: ConceptPair; pair_en: ConceptPair };
  despues: { pair_es: ConceptPair; pair_en: ConceptPair };
  motivo: string;
}

export interface ConceptsResponse {
  concepts: ConceptRow[];
}
